<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="curdasp1.aspx.cs" Inherits="ssssssv.curdasp1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:Label ID="Label1" runat="server" style="z-index: 1; left: 576px; top: 48px; position: absolute; width: 68px" Text="Id"></asp:Label>
            <asp:Label ID="Label2" runat="server" style="z-index: 1; left: 578px; top: 102px; position: absolute" Text="Name"></asp:Label>
            <asp:Label ID="Label3" runat="server" style="z-index: 1; left: 578px; top: 166px; position: absolute" Text="Gender"></asp:Label>
            <asp:Label ID="Label4" runat="server" style="z-index: 1; left: 582px; top: 227px; position: absolute" Text="PhoneNo"></asp:Label>
            <asp:Label ID="Label5" runat="server" style="z-index: 1; left: 588px; top: 289px; position: absolute" Text="Email"></asp:Label>
            <asp:Label ID="Label6" runat="server" style="z-index: 1; left: 580px; top: 344px; position: absolute; height: 26px" Text="Hobbies"></asp:Label>
            <asp:Label ID="Label7" runat="server" style="z-index: 1; left: 588px; top: 399px; position: absolute" Text="City"></asp:Label>
            <asp:TextBox ID="TextBox1" runat="server" style="z-index: 1; left: 709px; top: 46px; position: absolute"></asp:TextBox>
            <asp:TextBox ID="TextBox2" runat="server" style="z-index: 1; left: 712px; top: 103px; position: absolute"></asp:TextBox>
            <asp:TextBox ID="TextBox3" runat="server" style="z-index: 1; left: 720px; top: 225px; position: absolute"></asp:TextBox>
            <asp:TextBox ID="TextBox4" runat="server" style="z-index: 1; left: 724px; top: 291px; position: absolute"></asp:TextBox>
            <asp:Label ID="Label8" runat="server" style="z-index: 1; left: 586px; top: 453px; position: absolute" Text="Address"></asp:Label>
            <asp:RadioButton ID="RadioButton1" runat="server" GroupName="gender" style="z-index: 1; left: 714px; top: 168px; position: absolute" Text="Male" />
            <asp:RadioButton ID="RadioButton2" runat="server" GroupName="gender" style="z-index: 1; top: 165px; position: absolute; left: 805px" Text="FeMale" />
            <asp:CheckBox ID="CheckBox1" runat="server" style="z-index: 1; left: 729px; top: 345px; position: absolute" Text="Movies" />
            <asp:CheckBox ID="CheckBox2" runat="server" style="z-index: 1; left: 846px; top: 344px; position: absolute" Text="Cricket" />
            <asp:TextBox ID="TextBox5" runat="server" style="z-index: 1; left: 721px; top: 399px; position: absolute"></asp:TextBox>
            <asp:TextBox ID="TextBox6" runat="server" style="z-index: 1; left: 723px; top: 457px; position: absolute"></asp:TextBox>
            <asp:Button ID="Button1" runat="server" ForeColor="#6600FF" OnClick="Button1_Click" style="z-index: 1; left: 673px; top: 527px; position: absolute" Text="Submit" />
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" style="z-index: 1; left: 295px; top: 633px; position: absolute; height: 180px; width: 289px">
                <Columns>
                    <asp:TemplateField HeaderText="Id">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Id") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Name">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Bind("Name") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Gender">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Gender") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("Gender") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="PhoneNo">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("PhoneNo") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label4" runat="server" Text='<%# Bind("PhoneNo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Email">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("Email") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label5" runat="server" Text='<%# Bind("Email") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Hobbies">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox6" runat="server" Text='<%# Bind("Hobbies") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label6" runat="server" Text='<%# Bind("Hobbies") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="City">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox7" runat="server" Text='<%# Bind("City") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label7" runat="server" Text='<%# Bind("City") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Address">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox8" runat="server" Text='<%# Bind("Address") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label8" runat="server" Text='<%# Bind("Address") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
